
import React, { useEffect, useState } from 'react';
import { Layout } from '../components/Layout';
import { db } from '../services/db';
import { Job, Product } from '../types';
import { Button } from '../components/Button';
import { useNavigate, useParams } from 'react-router-dom';
import { Download, FileText, Share2 } from 'lucide-react';

export const JobsList: React.FC = () => {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [jobImages, setJobImages] = useState<Record<string, string>>({});
  const navigate = useNavigate();

  useEffect(() => {
    const load = async () => {
      const allJobs = await db.getJobs();
      setJobs(allJobs.sort((a, b) => b.createdAt - a.createdAt));
      
      const images: Record<string, string> = {};
      for (const j of allJobs) {
        if (j.renderedPreviewId) images[j.id] = await db.getAssetUrl(j.renderedPreviewId);
        else if (j.renderedPreviewUrl) images[j.id] = j.renderedPreviewUrl;
        else if (j.mainPhotoId) images[j.id] = await db.getAssetUrl(j.mainPhotoId);
      }
      setJobImages(images);
    };
    load();
  }, []);

  return (
    <Layout title="My Jobs">
      <div className="p-4 space-y-4">
        {jobs.map(job => (
          <div key={job.id} onClick={() => navigate(`/jobs/${job.id}`)} className="bg-white p-4 rounded-xl shadow-sm border border-slate-200 flex space-x-4 cursor-pointer hover:bg-slate-50">
             <div className="w-20 h-20 bg-slate-100 rounded-lg overflow-hidden shrink-0">
               <img src={jobImages[job.id]} className="w-full h-full object-cover" alt="" />
             </div>
             <div>
               <h3 className="font-bold text-slate-900">{job.name}</h3>
               <p className="text-sm text-slate-500">{new Date(job.createdAt).toLocaleDateString()}</p>
               <span className="inline-block mt-2 px-2 py-1 bg-green-100 text-green-700 text-xs rounded-full font-medium">
                 {job.status}
               </span>
             </div>
          </div>
        ))}
      </div>
    </Layout>
  );
};

export const JobDetail: React.FC = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [job, setJob] = useState<Job | null>(null);
  const [product, setProduct] = useState<Product | undefined>(undefined);
  const [profile, setProfile] = useState<any>(null);
  
  // Resolved Images
  const [previewUrl, setPreviewUrl] = useState('');
  const [originalUrl, setOriginalUrl] = useState('');
  const [textureUrl, setTextureUrl] = useState('');

  useEffect(() => {
    const load = async () => {
      if (id) {
        const j = await db.getJob(id);
        const prof = await db.getProfile();
        setProfile(prof);
        setJob(j || null);
        
        if (j) {
           // Resolve Preview
           if (j.renderedPreviewId) setPreviewUrl(await db.getAssetUrl(j.renderedPreviewId));
           else setPreviewUrl(j.renderedPreviewUrl || '');

           // Resolve Original
           if (j.mainPhotoId) setOriginalUrl(await db.getAssetUrl(j.mainPhotoId));
           else setOriginalUrl(j.mainPhotoUrl || '');
           
           if (j.productId) {
             const prods = await db.getProducts();
             const p = prods.find(prod => prod.id === j.productId);
             setProduct(p);
             if (p) {
                if (p.masterTextureId) setTextureUrl(await db.getAssetUrl(p.masterTextureId));
                else setTextureUrl(p.masterTextureUrl || '');
             }
           }
        }
      }
    };
    load();
  }, [id]);

  if (!job || !profile) return <div>Loading...</div>;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white min-h-screen pb-10">
      <div className="print:hidden sticky top-0 bg-white border-b z-20 px-4 py-3 flex justify-between items-center">
         <Button variant="secondary" size="sm" onClick={() => navigate(-1)}>Back</Button>
         <div className="flex space-x-2">
           <Button size="sm" onClick={() => navigate(`/visualizer/${job.id}`)}>Edit</Button>
           <Button variant="primary" size="sm" onClick={handlePrint}>
             <Download size={16} className="mr-2" /> Export PDF
           </Button>
         </div>
      </div>

      <div className="max-w-4xl mx-auto p-8 print:p-0" id="printable-area">
        <div className="border-b-2 border-slate-900 pb-6 mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-4xl font-extrabold text-slate-900 mb-2">JOB PACKAGE</h1>
            <p className="text-slate-500">Generated by SurfaceView</p>
          </div>
          <div className="text-right">
            <h2 className="text-xl font-bold">{profile.businessName}</h2>
            <p className="text-sm text-slate-600">{profile.contactName}</p>
            <p className="text-sm text-slate-600">{profile.phone}</p>
            <p className="text-sm text-slate-600">{profile.email}</p>
          </div>
        </div>

        <div className="mb-8 p-4 bg-slate-50 rounded-lg border border-slate-200 print:border-none print:bg-transparent print:p-0">
          <div className="grid grid-cols-2 gap-8">
            <div>
              <span className="text-xs font-bold text-slate-500 uppercase">Job Name</span>
              <p className="text-lg font-semibold">{job.name}</p>
            </div>
            <div>
              <span className="text-xs font-bold text-slate-500 uppercase">Date</span>
              <p className="text-lg font-semibold">{new Date(job.createdAt).toLocaleDateString()}</p>
            </div>
          </div>
        </div>

        <div className="mb-8">
          <h3 className="text-lg font-bold border-l-4 border-blue-600 pl-3 mb-4">Visualization</h3>
          <div className="aspect-video bg-slate-100 rounded-lg overflow-hidden border border-slate-200">
             <img src={previewUrl} className="w-full h-full object-contain" alt="Rendered Floor" />
          </div>
          <div className="mt-2 text-sm text-slate-500 italic">
             *Visualization is for illustrative purposes. Pattern scale and color may vary in real lighting.
          </div>
        </div>

        {product && (
          <div className="mb-8">
             <h3 className="text-lg font-bold border-l-4 border-blue-600 pl-3 mb-4">Product Specifications</h3>
             <div className="flex items-start space-x-6">
                <div className="w-32 h-32 bg-slate-100 rounded-lg overflow-hidden border">
                   <img src={textureUrl} className="w-full h-full object-cover" alt="Texture" />
                </div>
                <div>
                   <h4 className="text-xl font-bold">{product.name}</h4>
                   <div className="grid grid-cols-2 gap-x-8 gap-y-2 mt-4 text-sm">
                      <div className="flex justify-between border-b pb-1"><span>Type:</span> <span className="font-medium">{product.type}</span></div>
                      <div className="flex justify-between border-b pb-1"><span>Width:</span> <span className="font-medium">{product.widthMm}mm</span></div>
                      <div className="flex justify-between border-b pb-1"><span>Length:</span> <span className="font-medium">{product.lengthMm}mm</span></div>
                   </div>
                   {product.notes && <p className="mt-4 text-slate-600 text-sm bg-yellow-50 p-2 rounded">{product.notes}</p>}
                </div>
             </div>
          </div>
        )}

        <div className="break-inside-avoid">
           <h3 className="text-lg font-bold border-l-4 border-blue-600 pl-3 mb-4">Original Site Condition</h3>
           <div className="grid grid-cols-2 gap-4">
              <div className="aspect-video bg-slate-100 rounded-lg overflow-hidden border border-slate-200">
                <img src={originalUrl} className="w-full h-full object-cover" alt="Original Site" />
              </div>
           </div>
        </div>
      </div>
    </div>
  );
};
